### ISSUE TITLE
When a search result is clicked, open the corresponding info box on the right

### ISSUE THREAD

**Issue by alastair** [DDMAL/salzinnes-original#32]
Good idea?

**Comment by dellsystem** [comment]
Wait what does this mean, what info box?

**Comment by ahankinson** [comment]
I don't know what this means. What info box?

**Comment by alastair** [comment]
The one on the right. Expand the incipit that the search result is for

**Comment by dellsystem** [comment]
Oh. That sounds like a good idea. Is the incipit ID returned in the search results by any chance?

**Comment by cmotuz** [comment]
Hi Alastair, 

That sounds very good to me!

Catherine

**Comment by alastair** [comment]
woo! Catherine is here too!

@dellsystem yes, ID should included in everything

**Comment by alastair** [comment]
What should happen if you click on 1 result then another one on the same page. Should they stay open, or the other one close?

If you click on a result for page 1, then one on pg 2 then back to pg 1 the expanded element from 1 stays up. Should this close too?

**Comment by dellsystem** [comment]
Right now, I'm just storing the IDs of all the incipits that are opened and not subsequently closed in an array, and whenever the user scrolls to a new page, all the incipits in the array above are expanded. I don't make a distinction between incipits that are open due to a search query and those that are open due to a user clicking on them, because it's just easier that way.  However, if it's important for usability I can treat the incipits that should be open due to the search query differently - should I do this?

**Comment by ahankinson** [comment]
No, it's fine to treat them both the same way.

**Comment by dellsystem** [comment]
Ok great.
